// A synthesizable configurable divider

// NOTE: Generated by ChatGPT, because lazy
module pll_mod_divider #(
    parameter W = 8
)(
    input  wire             clk,
    input  wire             rst_n,     // active low reset
    input  wire [W-1:0]     set_div,   // new division value (>=1)
    input  wire             load_div,  // pulse to latch set_div into active divisor (synchronous)
    output reg              out        // divided clock output
);

    // active divisor
    reg [W-1:0] div;
    // counters and limits for alternating high/low when odd
    reg [W-1:0] cnt;
    reg [W-1:0] high_count, low_count;
    reg        high_phase; // 1 => currently producing high phase (counting high_count)

    // compute counts when div changes (synchronous)
    // high_count = ceil(div/2), low_count = floor(div/2)
    wire [W-1:0] half = div >> 1;
    wire        div_is_odd = div[0];

    always @(posedge clk or negedge rst_n) begin
        if(!rst_n) begin
            div        <= 1;
            cnt        <= 0;
            out        <= 0;
            high_phase <= 1'b0;
            high_count <= 1;
            low_count  <= 1;
        end else begin
            // update divisor synchronously on load_div
            if (load_div) begin
                // latch new divisor but sanitize: force >=1
                div <= (set_div == 0) ? 1 : set_div;
            end

            // recompute high/low counts when div changes
            // ensure at least 1
            if (div == 1) begin
                high_count <= 1;
                low_count  <= 1;
            end else if (div_is_odd) begin
                // odd: e.g., div=5 -> high=3, low=2
                high_count <= half + 1;
                low_count  <= half;
            end else begin
                // even: div=6 -> high=3 low=3
                high_count <= half;
                low_count  <= half;
            end

            // counting / toggling
            if (div == 1) begin
                // divide by 1: output follows input clock (toggle every cycle -> same freq)
                out <= ~out; // alternative: keep out = clk? but easier to toggle each cycle gives clk/2; depends on desired semantics
                cnt <= 0;
            end else begin
                // normal operation: count cycles within current phase
                if (cnt + 1 >= (high_phase ? high_count : low_count)) begin
                    // phase complete -> toggle output and start next phase
                    out <= ~out;
                    cnt <= 0;
                    high_phase <= ~high_phase;
                end else begin
                    cnt <= cnt + 1;
                end
            end
        end
    end

endmodule
