#!python

# Invoke me with:
# python3 ../src/create_sim_dco.py outputs/test_fine_delay.log outputs/test_mid_delay.log outputs/test_coarse_delay.log

import sys
from spice_io import meas_until_failed

def convert_simulation_to_verilog(fil, name):
    # The delays measured by measure_delay.sp, up to the first failed one
    values = meas_until_failed(fil, "tdel")

    nvalues = len(values)

    # Convert all values to the nearest integer, in fento-seconds
    str = ""
    for i in range(nvalues):
        v = values[i]
        iv = int(v * 1e15)
        if i == 0:
            str = str + (f"        if(MUX[{i}] == 1'b0) #({iv}); // delay = {v}\n")
        elif i != (nvalues-1):
            str = str + (f"        else if(MUX[{i}] == 1'b0) #({iv}); // delay = {v}\n")
        else:
            str = str + (f"        else #({iv}); // delay = {v}\n")

    return str

fine_str = convert_simulation_to_verilog(sys.argv[1], "FINE")
mid_str = convert_simulation_to_verilog(sys.argv[2], "MID")
coarse_str = convert_simulation_to_verilog(sys.argv[3], "COARSE")

str = f"""// NOTE: Automatically generated by create_sim_dco.py
// A digital VCO useful for digital simulations
`timescale 1fs/1fs

module sim_delay_fine #(
    parameter integer NDELS = 31
) (
    inout VDD, VSS,
    input [NDELS-1:0] MUX,
    input IN,
    output reg OUT
);
    initial OUT = 1'b0;
    always @(IN) begin
{fine_str}
        OUT = IN;
    end
endmodule

module sim_delay_mid #(
    parameter integer NDELS = 15
) (
    inout VDD, VSS,
    input [NDELS-1:0] MUX,
    input IN,
    output reg OUT
);
    initial OUT = 1'b0;
    always @(IN) begin
{mid_str}
        OUT = IN;
    end
endmodule

module sim_delay_coarse #(
    parameter integer NDELS = 15
) (
    inout VDD, VSS,
    input [NDELS-1:0] MUX,
    input IN,
    output reg OUT
);
    initial OUT = 1'b0;
    always @(IN) begin
{coarse_str}
        OUT = IN;
    end
endmodule
"""

print(str)
