#!python

# Invoke me with:
# python3 ../src/create_sim_dco.py outputs/test_fine_delay.mt0 outputs/test_mid_delay.mt0 outputs/test_coarse_delay.mt0

import re, sys

def convert_simulation_to_verilog(fil, name):
    with open(fil) as f:
        data = f.read()

    lines = data.splitlines()

    # 1. Extract column names (between .TITLE and the numeric block)
    header_lines = []
    data_lines = []
    in_data = False

    for line in lines:
        if in_data:
            data_lines.append(line)
        elif line.strip() and not line.startswith(('$DATA', '.TITLE')):
            header_lines.append(line)
        if re.search(r'alter', line.strip()):  # line has numbers
            in_data = True

    # 2. Join and split by whitespace
    headers = re.split(r'\s+', " ".join(header_lines).strip())
    values = re.split(r'\s+', " ".join(data_lines).strip())

    # How many values actually exist?
    nvalues = 32
    for i, v in enumerate(values):
        if v == "failed":
            nvalues = i
            break

    # Convert all values to the nearest integer, in fento-seconds
    str = ""
    for i in range(nvalues):
        v = float(values[i])
        iv = int(v * 1e15)
        if i == 0:
            str = str + (f"        if(MUX[{i}] == 1'b0) #({iv}); // delay = {v}\n")
        elif i != (nvalues-1):
            str = str + (f"        else if(MUX[{i}] == 1'b0) #({iv}); // delay = {v}\n")
        else:
            str = str + (f"        else #({iv}); // delay = {v}\n")

    return str

fine_str = convert_simulation_to_verilog(sys.argv[1], "FINE")
mid_str = convert_simulation_to_verilog(sys.argv[2], "MID")
coarse_str = convert_simulation_to_verilog(sys.argv[3], "COARSE")

str = f"""// NOTE: Automatically generated by create_sim_dco.py
// A digital VCO useful for digital simulations
`timescale 1fs/1fs

module sim_delay_fine #(
    parameter integer NDELS = 31
) (
    inout VDD, VSS,
    input [NDELS-1:0] MUX,
    input IN,
    output reg OUT
);
    initial OUT = 1'b0;
    always @(IN) begin
{fine_str}
        OUT = IN;
    end
endmodule

module sim_delay_mid #(
    parameter integer NDELS = 15
) (
    inout VDD, VSS,
    input [NDELS-1:0] MUX,
    input IN,
    output reg OUT
);
    initial OUT = 1'b0;
    always @(IN) begin
{mid_str}
        OUT = IN;
    end
endmodule

module sim_delay_coarse #(
    parameter integer NDELS = 15
) (
    inout VDD, VSS,
    input [NDELS-1:0] MUX,
    input IN,
    output reg OUT
);
    initial OUT = 1'b0;
    always @(IN) begin
{coarse_str}
        OUT = IN;
    end
endmodule
"""

print(str)
