#!python

# Invoke me with:
# python3 ../src/create_sim_sym.py outputs/test_sym_delay.log

import sys
from spice_io import read_meas

def convert_simulation_to_verilog(fil):
    meas = read_meas(fil)

    # Convert all values to the nearest integer, in fento-seconds
    str = ""
    v1 = meas["tmux"]
    iv1 = int(v1 * 1e15)
    str = str + (f"    always @(OUT_WIRE) OUT = #({iv1}) OUT_WIRE; // tmux = {v1}\n")
    
    v2 = meas["tssbbpd"]
    iv2 = int(v2 * 1e15)
    str = str + (f"    always @(SS_BBPD_WIRE) SS_BBPD = #({iv2}) SS_BBPD_WIRE; // tssbbpd = {v2}\n")

    return str

always_str = convert_simulation_to_verilog(sys.argv[1])

str = f"""// NOTE: Automatically generated by create_sim_inj.py
// Digital-simulated definition of
// The total implementation of Symmetrical Multiplexer and Symmetrical SSBBPD

module sim_SYM (
    inout VDD, VSS, // ignored
    input INJ_WIN, DCO_EN,
    input INJ_EDGE, FINE_OUT,
    output reg [1:0] SS_BBPD,
    output reg OUT
);
    // Symmetric balancer (Nothing)
    wire OSC_BALANCED, INJ_EDGE_BALANCED;
    assign OSC_BALANCED = !FINE_OUT;
    assign INJ_EDGE_BALANCED = !INJ_EDGE;

    // Sym. MUX
    wire DCO_EN_INJ_WIN;
    assign DCO_EN_INJ_WIN = !(!DCO_EN || INJ_WIN); // NOR2B

    wire OSC_INJ, REF_INJ;
    assign REF_INJ = !(!INJ_EDGE_BALANCED && INJ_WIN); // NAND2B
    assign OSC_INJ = !(OSC_BALANCED && DCO_EN_INJ_WIN); // NAND2
    wire OUT_WIRE = !(REF_INJ && OSC_INJ);

    // Subsampling bang-bang PD (SS-BBPD)
    wire [1:0] SS_BBPD_WIRE;
    sim_SSBBPD ssbbpd_impl(
        .CLK_REF(INJ_EDGE_BALANCED), .CLK_VCO(OSC_BALANCED),
        .SS_BBPD(SS_BBPD_WIRE));

{always_str}

endmodule
"""

print(str)
