#!python

# Invoke me with:
# python3 ../src/create_sim_inj.py outputs/test_pll_injection.log

import sys
from spice_io import read_meas

def convert_simulation_to_verilog(fil):
    meas = read_meas(fil)

    # Convert all values to the nearest integer, in fento-seconds
    str = ""
    
    v3 = meas["tedge_start"]
    iv3 = int(v3 * 1e15)
    str = str + (f"    always @(REF) INJ_EDGE = #({iv3}) REF; // tedge_start = {v3}\n")
    
    v1 = meas["twin_start"]
    iv1 = int(v1 * 1e15)
    str = str + (f"    always @(REF) DEL_REF = #({iv1}) REF; // twin_start = {v1}\n")
    
    v2 = meas["twin_len"]
    iv2 = int(v2 * 1e15)
    str = str + (f"    always @(REF) DEL_EDGE = #({iv1} + {iv2}) REF; // twin_start + twin_len = {v1} + {v2}\n")

    return str

always_str = convert_simulation_to_verilog(sys.argv[1])

str = f"""// NOTE: Automatically generated by create_sim_inj.py
// Simulation model of the PLL_INJECTION
`timescale 1fs/1fs

module sim_pll_injection # (
    parameter integer NDELS = 4,
    parameter integer VERSION = 1 // 0 for AND-based, 1 for NOR-based
) (
    inout VDD, VSS, // ignored
    input REF, INJ_EN,
    output reg INJ_EDGE, 
    output INJ_WIN
);
    reg DEL_REF, DEL_EDGE;

    // Extracted from test_pll_injection.sp
{always_str}
    // Generation of the window
    assign INJ_WIN = !DEL_REF && DEL_EDGE && INJ_EN;
endmodule
"""

print(str)
