#!python

# Phase noise of the DCO with the ISF (impulse sensitivity function) method
# (A. Hajimiri and T. H. Lee, "A general theory of phase noise in electrical oscillators", JSSC 1998)
#
# Needs the runs generated by create_isf.py (run inside sim/outputs/<PDK>):
# python3 ../../src/isf_phase_noise.py
#
# 1. ISF: for each oscillating net n, the permanent shift of the OUT edges after injecting
#    a charge dq at the phase x of the period gives h_n(x) = dphi/dq (rad/C).
#    (Gamma_n(x) = h_n(x) * qmax_n in the normalized form of the paper)
# 2. Noise: the drain current noise of every transistor along the steady-state period,
#    S(f, x) = Sth(x) + K(x) / f^ef, interpolated from the .noise tables at its Vgs(x), Vds(x).
#    (cyclostationary noise, so this already includes the noise modulation function)
# 3. Each transistor noise current flows from drain to source, so it couples with
#    h_dev(x) = h_s(x) - h_d(x) (0 for nets that are not oscillating, e.g. supplies)
#
#    White (1/f^2 region):   S_phi(df) = sum_dev mean_x(h_dev^2 Sth) / (2 pi df)^2
#    Flicker (1/f^3 region): S_phi(df) = sum_dev mean_x(h_dev sqrt(K))^2 / df^ef / (2 pi df)^2
#    L(df) = S_phi(df) / 2 (single sideband, dBc/Hz)

import json, re, sys
import numpy as np
from spice_io import read_raw

NX = 256                                 # Points of the period for the averages
FREQS = np.logspace(2, 9, 71)            # Offset frequencies (Hz)
REPORT = [1e3, 1e4, 1e5, 1e6, 1e7, 1e8]  # Offsets printed in the summary

def crossings(t, v, th):
    i = np.where((v[:-1] < th) & (v[1:] >= th))[0]
    return t[i] + (th - v[i]) * (t[i + 1] - t[i]) / (v[i + 1] - v[i])

def edges_of(raw, out, th):
    d = read_raw(raw)
    return crossings(d["time"], d[f"v({out})"], th)

def isf(setup, ref_edges, run):
    """Samples (x, h) of the ISF of one net, plus the rms numerical error of the edge times"""
    T = setup["T"]
    pert = edges_of(f"{run}.raw", setup["out"], setup["vdd"] / 2)
    n = min(len(pert), len(ref_edges))
    dt = pert[:n] - ref_edges[:n]
    tref = ref_edges[:n]
    tinj = setup["tinj"] + [setup["tinj"][-1] + setup["nper"] * T]
    xs, hs, err = [], [], []
    for k in range(len(setup["tinj"])):
        # Mean edge shift in the period before this injection and before the next one
        before = dt[(tref > tinj[k] - 1.5 * T) & (tref < tinj[k])]
        after = dt[(tref > tinj[k + 1] - 1.5 * T) & (tref < tinj[k + 1])]
        if len(before) == 0 or len(after) == 0:
            continue
        # Actual phase of the injection with respect to the (perturbed) rising edge of OUT
        last = pert[:n][pert[:n] <= tinj[k]]
        if len(last) == 0:
            continue
        xs.append(((tinj[k] - last[-1]) / T) % 1.0)
        # A delay (positive shift) is a negative phase step
        hs.append(-2 * np.pi * (after.mean() - before.mean()) / T / setup["dq"])
        err += list(before - before.mean())
    order = np.argsort(xs)
    return np.array(xs)[order], np.array(hs)[order], float(np.sqrt(np.mean(np.square(err)))) if err else 0.0

def read_lut(log):
    """Noise table: grid of |Vgs|, |Vds| -> spectrum at 1e3..1e10 Hz (A^2/Hz)"""
    points = []
    cur = None
    with open(log) as f:
        lines = f.read().splitlines()
    for i, line in enumerate(lines):
        m = re.match(r'^lut_(vgs|vds)\s*=\s*(\S+)', line)
        if m:
            if m.group(1) == "vgs":
                cur = [abs(float(m.group(2))), None, []]
                points.append(cur)
            else:
                cur[1] = abs(float(m.group(2)))
            continue
        m = re.match(r'^\s*\d+\s+([\d.e+-]+)\s+([\d.e+-]+)\s*$', line)
        if m and cur is not None:
            cur[2].append((float(m.group(1)), float(m.group(2)) ** 2))
    vgs = np.unique([p[0] for p in points])
    vds = np.unique([p[1] for p in points])
    freqs = np.array([f for f, _ in points[0][2]])
    spec = np.zeros((len(vgs), len(vds), len(freqs)))
    for g, d, s in points:
        spec[np.searchsorted(vgs, g), np.searchsorted(vds, d)] = [v for _, v in s]
    # Fit S = Sth + K/f^ef: thermal at the highest frequency, ef from the two lowest ones
    sth = spec[:, :, -1]
    fl1 = np.maximum(spec[:, :, 0] - sth, 0)
    fl2 = np.maximum(spec[:, :, 1] - sth, 0)
    ok = (fl1 > 0) & (fl2 > 0)
    ef = float(np.median(np.log10(fl1[ok] / fl2[ok]) / np.log10(freqs[1] / freqs[0]))) if ok.any() else 1.0
    k = fl1 * freqs[0] ** ef
    return dict(vgs=vgs, vds=vds, sth=sth, k=k, ef=ef)

def interp2(lut, table, vgs, vds):
    """Bilinear interpolation on the grid (clipped to its range)"""
    gx, dx = lut["vgs"], lut["vds"]
    vgs = np.clip(vgs, gx[0], gx[-1])
    vds = np.clip(vds, dx[0], dx[-1])
    i = np.clip(np.searchsorted(gx, vgs) - 1, 0, len(gx) - 2)
    j = np.clip(np.searchsorted(dx, vds) - 1, 0, len(dx) - 2)
    a = (vgs - gx[i]) / (gx[i + 1] - gx[i])
    b = (vds - dx[j]) / (dx[j + 1] - dx[j])
    return ((1 - a) * (1 - b) * table[i, j] + a * (1 - b) * table[i + 1, j]
            + (1 - a) * b * table[i, j + 1] + a * b * table[i + 1, j + 1])

def main():
    with open("isf_setup.json") as f:
        setup = json.load(f)
    T, vdd = setup["T"], setup["vdd"]
    x = np.arange(NX) / NX

    # 1. ISF of every oscillating net
    ref_edges = edges_of("isf_ref.raw", setup["out"], vdd / 2)
    h = {}
    print(f"f0 = {1/T/1e9:.6g} GHz")
    print(f"{'net':45s} {'h_rms':>12s} {'h_dc':>12s} {'edge err':>9s}")
    for node in setup["nodes"]:
        xs, hs, err = isf(setup, ref_edges, node["name"])
        # Periodic interpolation onto the uniform grid
        h[node["net"]] = np.interp(x, xs, hs, period=1.0)
        hrms = np.sqrt(np.mean(h[node["net"]] ** 2))
        print(f"{node['net']:45s} {hrms*1e-15:9.4g} rad/fC {np.mean(h[node['net']])*1e-15:9.4g} rad/fC {err*1e15:6.2f} fs")

    # 2. Waveforms of one steady-state period, starting at a rising edge of OUT
    wave = read_raw("test_dco_isf_wave.raw")
    t = wave["time"]
    e = crossings(t, wave[f"v({setup['out']})"], vdd / 2)
    tx = e[-2] + x * T
    def v(net):
        return np.zeros(NX) if net == "0" else np.interp(tx, t, wave[f"v({net})"])

    luts = {l["key"]: dict(read_lut(f"{l['name']}.log"), type=l["type"]) for l in setup["luts"]}

    # 3. Contribution of every transistor
    white = {}
    flick = {}
    efs = {}
    for dev in setup["devices"]:
        hd = h.get(dev["d"], 0.0)
        hsrc = h.get(dev["s"], 0.0)
        if np.isscalar(hd) and np.isscalar(hsrc):
            continue
        hdev = (hsrc if not np.isscalar(hsrc) else 0) - (hd if not np.isscalar(hd) else 0)
        lut = luts[dev["key"]]
        sign = 1 if lut["type"] == "n" else -1
        vd, vg, vs = v(dev["d"]), v(dev["g"]), v(dev["s"])
        vgs, vds = sign * (vg - vs), sign * (vd - vs)
        # Drain and source swap when Vds < 0
        swap = vds < 0
        vgs = np.where(swap, sign * (vg - vd), vgs)
        vds = np.abs(vds)
        sth = dev["m"] * interp2(lut, lut["sth"], vgs, vds)
        k = dev["m"] * interp2(lut, lut["k"], vgs, vds)
        net = dev["d"] if not np.isscalar(hd) else dev["s"]
        white[net] = white.get(net, 0) + np.mean(hdev ** 2 * sth)
        flick[net] = flick.get(net, 0) + np.mean(hdev * np.sqrt(k)) ** 2
        efs[net] = lut["ef"]

    ef = float(np.mean(list(efs.values())))
    w = sum(white.values())
    fl = sum(flick.values())
    s_white = w / (2 * np.pi * FREQS) ** 2
    s_flick = fl / FREQS ** ef / (2 * np.pi * FREQS) ** 2
    L = 10 * np.log10((s_white + s_flick) / 2)
    corner = (fl / w) ** (1 / ef) if w > 0 and fl > 0 else 0.0

    print(f"\nFlicker exponent ef = {ef:.3f}, 1/f^3 corner = {corner/1e3:.4g} kHz")
    for f0 in REPORT:
        i = np.argmin(np.abs(FREQS - f0))
        print(f"L({FREQS[i]:8.3g} Hz) = {L[i]:7.2f} dBc/Hz")
    print("\nTop contributors at 1 MHz (white + flicker):")
    tot = {n: white.get(n, 0) + flick.get(n, 0) / 1e6 ** ef for n in white}
    for n, c in sorted(tot.items(), key=lambda kv: -kv[1])[:8]:
        print(f"  {n:45s} {100 * c / sum(tot.values()):5.1f} %")

    with open("test_dco_noise.csv", "w") as f:
        f.write("freq,L_dBc_Hz,L_white_dBc_Hz,L_flicker_dBc_Hz\n")
        for i, fr in enumerate(FREQS):
            f.write(f"{fr:.6g},{L[i]:.4f},{10*np.log10(s_white[i]/2):.4f},{10*np.log10(max(s_flick[i], 1e-300)/2):.4f}\n")

    import matplotlib.pyplot as plt
    fig, (a1, a2) = plt.subplots(2, 1, figsize=(8, 9))
    for n in sorted(h, key=lambda n: -np.sqrt(np.mean(h[n] ** 2)))[:8]:
        a1.plot(x, h[n] * 1e-15, label=n)
    a1.set_xlabel("Phase (fraction of the period, 0 = OUT rising)")
    a1.set_ylabel("ISF h(x) (rad/fC)")
    a1.set_title("ISF of the nets with the largest h_rms")
    a1.legend(fontsize=6)
    a1.grid(True)
    a2.semilogx(FREQS, L, "r", label="Total")
    a2.semilogx(FREQS, 10 * np.log10(s_white / 2), "b--", label="Thermal (1/f$^2$)")
    a2.semilogx(FREQS, 10 * np.log10(np.maximum(s_flick, 1e-300) / 2), "g--", label="Flicker (1/f$^3$)")
    a2.set_ylim(np.min(L) - 10, np.max(L) + 10)
    a2.set_xlabel("Offset frequency (Hz)")
    a2.set_ylabel("L (dBc/Hz)")
    a2.set_title(f"DCO phase noise (ISF), f0 = {1/T/1e9:.4g} GHz")
    a2.grid(True, which="both")
    a2.legend()
    fig.tight_layout()
    fig.savefig("test_dco_noise.pdf")
    print("\nWritten test_dco_noise.csv and test_dco_noise.pdf")

if __name__ == "__main__":
    main()
